import type { Product, ProductColor } from "@/types/product";

/**
 * Product catalogue. This is the single source of truth for the storefront — swap
 * `src/lib/products.ts` to fetch from an API/CMS later and nothing else has to change.
 *
 * NOTE: materials, dimensions, ratings, delivery and return terms below are placeholders —
 * confirm every value with the Beanify team before launch.
 * Images are placeholders generated by `scripts/generate-art.mjs`; replace with real photography.
 */

const shots = ["front", "room", "detail"] as const;
const gallery = (slug: string, color: string) =>
  shots.map((s) => `/images/products/${slug}/${color}-${s}.webp`);

const colour = (slug: string, name: string, hex: string): ProductColor => ({
  name,
  hex,
  images: gallery(slug, name.toLowerCase()),
});

const SHIPPING =
  "Ships across India. Most orders are delivered in 5–7 working days after confirmation on WhatsApp. We'll share the exact timeline and tracking once your order is confirmed.";
const RETURNS =
  "Received something damaged or not as described? Message us on WhatsApp within 7 days of delivery with photos and we'll arrange a replacement or refund. Products should be unused and in original packaging for change-of-mind requests.";
const CARE = [
  "Spot clean with a damp cloth and mild soap.",
  "Do not machine wash the inner liner.",
  "Keep away from direct heat, sharp objects and prolonged direct sunlight.",
  "Fluff and rotate regularly to keep the shape.",
];
const LOVE = [
  { title: "Instant comfort", text: "Moulds to your body so you can sink in and stay a while." },
  { title: "Made to be seen", text: "A clean, modern silhouette that looks as good as it feels." },
  { title: "Easy to move", text: "Light enough to shift from the living room to the balcony." },
  { title: "Built for daily life", text: "Durable fabric and reinforced seams for everyday use." },
];

export const products: Product[] = [
  {
    id: "beanify-classic",
    slug: "beanify-classic",
    name: "Beanify Classic",
    shortDescription: "Premium everyday comfort bean bag",
    description:
      "The bean bag that started it all. Beanify Classic pairs a soft, supportive fill with a clean teardrop shape that hugs you the moment you sit. It's the easy, everyday spot for reading, scrolling and doing absolutely nothing — in a colour that suits your room.",
    price: 2999,
    category: "Bean Bags",
    badge: "Bestseller",
    featured: true,
    createdAt: "2026-01-10",
    images: gallery("beanify-classic", "burgundy"),
    colors: [colour("beanify-classic", "Burgundy", "#781C2E"), colour("beanify-classic", "Beige", "#D8C4A4"), colour("beanify-classic", "Black", "#2B2426")],
    sizes: [
      { name: "Large", detail: "Approx. 90 × 90 × 95 cm · ideal for 1 adult", price: 2999 },
      { name: "XL", detail: "Approx. 100 × 100 × 105 cm · roomy for 1 adult", price: 3499 },
      { name: "XXL", detail: "Approx. 110 × 110 × 115 cm · extra-generous", price: 3999 },
    ],
    rating: 4.9,
    reviewCount: 128,
    specifications: [
      { label: "Shape", value: "Classic teardrop" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Durable woven fabric, zip closure" },
      { label: "Weight", value: "Approx. 2.5–3.5 kg (varies by size)" },
    ],
    material: "Durable woven outer cover with a soft inner liner and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-lounger",
    slug: "beanify-lounger",
    name: "Beanify Lounger",
    shortDescription: "Low, long & made for stretching out",
    description:
      "Beanify Lounger is a long, low profile designed for full-body lounging. Prop yourself up with a book, stretch out for a movie or fold up a guest — it makes any corner feel like a retreat.",
    price: 3799,
    category: "Loungers",
    badge: "Bestseller",
    featured: true,
    createdAt: "2026-02-02",
    images: gallery("beanify-lounger", "beige"),
    colors: [colour("beanify-lounger", "Beige", "#D8C4A4"), colour("beanify-lounger", "Burgundy", "#781C2E"), colour("beanify-lounger", "Sage", "#97A583")],
    sizes: [
      { name: "Large", detail: "Approx. 150 × 80 × 55 cm · ideal for 1 adult", price: 3799 },
      { name: "XL", detail: "Approx. 170 × 90 × 60 cm · stretch-out size", price: 4499 },
    ],
    rating: 4.8,
    reviewCount: 74,
    specifications: [
      { label: "Shape", value: "Reclined lounger" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Soft-touch woven fabric, zip closure" },
      { label: "Best for", value: "Reading, movies, naps" },
    ],
    material: "Soft-touch woven outer cover with an inner liner and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-xl",
    slug: "beanify-xl",
    name: "Beanify XL",
    shortDescription: "Extra-large comfort, extra-large spot",
    description:
      "More room, more sink, more comfort. Beanify XL is built for taller frames and longer sessions — the go-to for movie nights, gaming marathons and lazy Sundays.",
    price: 3999,
    category: "Bean Bags",
    badge: "Popular",
    featured: true,
    createdAt: "2026-02-20",
    images: gallery("beanify-xl", "black"),
    colors: [colour("beanify-xl", "Black", "#2B2426"), colour("beanify-xl", "Burgundy", "#781C2E"), colour("beanify-xl", "Tan", "#B27A4A")],
    sizes: [
      { name: "XXL", detail: "Approx. 110 × 110 × 115 cm · extra-generous", price: 3999 },
      { name: "XXXL", detail: "Approx. 120 × 120 × 125 cm · the biggest we make", price: 4699 },
    ],
    rating: 4.8,
    reviewCount: 61,
    specifications: [
      { label: "Shape", value: "Oversized teardrop" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Reinforced woven fabric, zip closure" },
      { label: "Best for", value: "Taller users, gaming, movie nights" },
    ],
    material: "Reinforced woven outer cover with an inner liner and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-kids",
    slug: "beanify-kids",
    name: "Beanify Kids",
    shortDescription: "Pint-sized comfort for little ones",
    description:
      "A smaller, softer Beanify made for kids' rooms and play corners. Lightweight so little hands can move it, with a playful pattern and a cover that shrugs off everyday mess.",
    price: 1999,
    category: "Bean Bags",
    badge: "New",
    featured: true,
    createdAt: "2026-06-12",
    images: gallery("beanify-kids", "blush"),
    colors: [colour("beanify-kids", "Blush", "#E2B2A8"), colour("beanify-kids", "Burgundy", "#781C2E"), colour("beanify-kids", "Sage", "#97A583")],
    sizes: [
      { name: "Kids", detail: "Approx. 60 × 60 × 65 cm · ages 3–10", price: 1999 },
      { name: "Junior", detail: "Approx. 70 × 70 × 75 cm · ages 8–14", price: 2399 },
    ],
    rating: 4.9,
    reviewCount: 39,
    specifications: [
      { label: "Shape", value: "Compact teardrop" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Wipe-clean printed fabric, child-safe zip" },
      { label: "Ages", value: "3–14 years" },
    ],
    material: "Wipe-clean printed fabric cover with a child-safe zip and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-premium",
    slug: "beanify-premium",
    name: "Beanify Premium",
    shortDescription: "Textured bouclé-look finish, elevated",
    description:
      "Our most elevated bean bag. A richly textured bouclé-look cover gives Beanify Premium a soft, sculptural finish that feels right at home in a considered, design-led space.",
    price: 4999,
    category: "Bean Bags",
    badge: "New",
    featured: true,
    createdAt: "2026-07-01",
    images: gallery("beanify-premium", "ivory"),
    colors: [colour("beanify-premium", "Ivory", "#EFE6D5"), colour("beanify-premium", "Burgundy", "#781C2E"), colour("beanify-premium", "Charcoal", "#4A4547")],
    sizes: [
      { name: "Large", detail: "Approx. 90 × 90 × 95 cm · ideal for 1 adult", price: 4999 },
      { name: "XL", detail: "Approx. 100 × 100 × 105 cm · roomy for 1 adult", price: 5699 },
    ],
    rating: 5,
    reviewCount: 27,
    specifications: [
      { label: "Shape", value: "Sculpted teardrop" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Textured bouclé-look fabric, hidden zip" },
      { label: "Finish", value: "Double-stitched seams" },
    ],
    material: "Textured bouclé-look outer fabric with an inner liner and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-floor-pouf",
    slug: "beanify-floor-pouf",
    name: "Beanify Floor Pouf",
    shortDescription: "Soft, low seating for any corner",
    description:
      "A tufted, low pouf that works as a floor seat, footrest or extra guest seating. Small enough to tuck away, good-looking enough to leave out.",
    price: 1799,
    category: "Floor Seating",
    featured: true,
    createdAt: "2026-03-15",
    images: gallery("beanify-floor-pouf", "blush"),
    colors: [colour("beanify-floor-pouf", "Blush", "#E2B2A8"), colour("beanify-floor-pouf", "Burgundy", "#781C2E"), colour("beanify-floor-pouf", "Beige", "#D8C4A4")],
    sizes: [
      { name: "Medium", detail: "Approx. 45 × 45 × 35 cm · seat or footrest", price: 1799 },
      { name: "Large", detail: "Approx. 60 × 60 × 40 cm · floor seat", price: 2199 },
    ],
    rating: 4.7,
    reviewCount: 45,
    specifications: [
      { label: "Shape", value: "Round tufted pouf" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Woven fabric with top button detail" },
      { label: "Use", value: "Seat, footrest, side seating" },
    ],
    material: "Woven fabric cover with a tufted top and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-cloud-cushion",
    slug: "beanify-cloud-cushion",
    name: "Beanify Cloud Cushion",
    shortDescription: "Oversized, plush accent cushion",
    description:
      "An oversized, ultra-soft accent cushion for sofas, beds and reading nooks. Pinched corners and a centre button give it a relaxed, sculpted look.",
    price: 899,
    category: "Cushions",
    createdAt: "2026-04-05",
    images: gallery("beanify-cloud-cushion", "beige"),
    colors: [colour("beanify-cloud-cushion", "Beige", "#D8C4A4"), colour("beanify-cloud-cushion", "Burgundy", "#781C2E"), colour("beanify-cloud-cushion", "Sage", "#97A583"), colour("beanify-cloud-cushion", "Black", "#2B2426")],
    sizes: [
      { name: "Medium", detail: "Approx. 45 × 45 cm", price: 899 },
      { name: "Large", detail: "Approx. 60 × 60 cm", price: 1199 },
    ],
    rating: 4.8,
    reviewCount: 52,
    specifications: [
      { label: "Shape", value: "Square with centre button" },
      { label: "Filling", value: "Soft microfibre" },
      { label: "Cover", value: "Removable woven cover, hidden zip" },
      { label: "Use", value: "Sofa, bed, reading nook" },
    ],
    material: "Removable woven cover with soft microfibre filling.",
    care: [
      "Cover is removable — spot clean or hand wash gently in cold water.",
      "Do not bleach or tumble dry.",
      "Air dry away from direct sunlight.",
      "Plump regularly to keep the shape.",
    ],
    shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
  {
    id: "beanify-gamer",
    slug: "beanify-gamer",
    name: "Beanify Gamer",
    shortDescription: "Long-session comfort with a bold edge",
    description:
      "Built for long sessions. Beanify Gamer has extra support through the back, a wipe-friendly finish and contrast piping that looks sharp in any setup.",
    price: 3499,
    category: "Bean Bags",
    badge: "New",
    createdAt: "2026-06-25",
    images: gallery("beanify-gamer", "black"),
    colors: [colour("beanify-gamer", "Black", "#2B2426"), colour("beanify-gamer", "Burgundy", "#781C2E"), colour("beanify-gamer", "Charcoal", "#4A4547")],
    sizes: [
      { name: "Large", detail: "Approx. 90 × 90 × 95 cm · ideal for 1 adult", price: 3499 },
      { name: "XL", detail: "Approx. 100 × 100 × 105 cm · roomy for 1 adult", price: 3999 },
    ],
    rating: 4.8,
    reviewCount: 33,
    specifications: [
      { label: "Shape", value: "Supportive teardrop" },
      { label: "Filling", value: "Premium EPS beans" },
      { label: "Cover", value: "Wipe-friendly woven fabric with contrast piping" },
      { label: "Best for", value: "Gaming, streaming, long sessions" },
    ],
    material: "Wipe-friendly woven fabric with contrast piping and premium EPS bean filling.",
    care: CARE, shipping: SHIPPING, returns: RETURNS, highlights: LOVE,
  },
];
